# Generated by Django 5.1.15 on 2025-12-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_dosen_nidn'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCollage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Foto Galeri', max_length=100)),
                ('gambar', models.ImageField(upload_to='asset/')),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampil di galeri')),
            ],
            options={
                'verbose_name_plural': 'Photo Collage',
                'ordering': ['urutan'],
            },
        ),
    ]
